# Generated by Django 6.1.1 on 2026-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='نام مشتری')),
                ('phone', models.CharField(help_text='این شماره مبنای کد پیگیری خواهد بود', max_length=20, verbose_name='شماره تماس مشتری')),
                ('tracking_code', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='کد پیگیری')),
                ('device_type', models.CharField(choices=[('pc', 'سیستم (کیس)'), ('laptop', 'لپ\u200cتاپ'), ('printer', 'پرینتر'), ('monitor', 'مانیتور'), ('network', 'تجهیزات شبکه'), ('other', 'سایر')], default='pc', max_length=20, verbose_name='نوع دستگاه')),
                ('device_model', models.CharField(blank=True, max_length=150, verbose_name='مدل / برند دستگاه')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='شماره سریال (در صورت وجود)')),
                ('problem_description', models.TextField(verbose_name='شرح مشکل / درخواست مشتری')),
                ('status', models.CharField(choices=[('received', 'دریافت شده'), ('in_progress', 'در حال بررسی'), ('repairing', 'در حال تعمیر'), ('waiting_parts', 'در انتظار قطعه'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده'), ('canceled', 'لغو شده')], default='received', max_length=20, verbose_name='وضعیت')),
                ('technician_notes', models.TextField(blank=True, help_text='این بخش برای مشتری نمایش داده نمی\u200cشود', verbose_name='یادداشت\u200cهای فنی (داخلی)')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='هزینه تخمینی (تومان)')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ دریافت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
            ],
            options={
                'verbose_name': 'کیس تعمیر',
                'verbose_name_plural': 'کیس\u200cهای تعمیر',
                'ordering': ['-received_at'],
            },
        ),
    ]
