# Generated by Django 6.1.1 on 2026-09-27 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccompanyingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً: شارژر، کیف، ماوس، کابل برق', max_length=150, verbose_name='نام قلم')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('note', models.CharField(blank=True, help_text='مثلاً: کمی فرسوده، رنگ مشکی', max_length=200, verbose_name='توضیح (اختیاری)')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accompanying_items', to='support.repaircase', verbose_name='کیس تعمیر')),
            ],
            options={
                'verbose_name': 'قلم همراه دستگاه',
                'verbose_name_plural': 'اقلام همراه دستگاه',
            },
        ),
    ]
