# Generated by Django 6.1.1 on 2026-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='دفتر ما', max_length=150, verbose_name='نام سایت / دفتر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('tagline', models.CharField(blank=True, help_text='مثلاً: خدمات تعمیرات تخصصی', max_length=200, verbose_name='شعار کوتاه سایت')),
                ('hero_title', models.CharField(default='به دفتر ما خوش آمدید', max_length=200, verbose_name='عنوان اصلی صفحه نخست')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='توضیح زیر عنوان اصلی')),
                ('address', models.TextField(blank=True, verbose_name='آدرس دفتر')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='شماره تماس دفتر')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('working_hours', models.CharField(blank=True, help_text='مثلاً: شنبه تا چهارشنبه، ۹ الی ۱۸', max_length=150, verbose_name='ساعات کاری')),
                ('map_embed_url', models.URLField(blank=True, verbose_name='لینک نقشه (Google Maps Embed)')),
                ('instagram_url', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram_url', models.URLField(blank=True, verbose_name='تلگرام')),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, verbose_name='شماره واتساپ')),
                ('urgent_support_title', models.CharField(default='پشتیبانی فوری', max_length=150, verbose_name='عنوان پشتیبانی فوری')),
                ('urgent_support_text', models.TextField(blank=True, default='برای دریافت پشتیبانی فوری با شماره زیر تماس بگیرید.', verbose_name='توضیح پشتیبانی فوری')),
                ('urgent_support_phone', models.CharField(blank=True, max_length=30, verbose_name='شماره تماس پشتیبانی فوری')),
                ('about_text', models.TextField(blank=True, verbose_name='متن درباره\u200cی دفتر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
