# Generated by Django 6.1.1 on 2026-10-01 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام نرم\u200cافزار')),
            ],
            options={
                'verbose_name': 'نرم\u200cافزار',
                'verbose_name_plural': 'نرم\u200cافزارها',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='نام شرکت / کسب\u200cوکار')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='کد ملی')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='شماره موبایل')),
                ('landline', models.CharField(blank=True, max_length=20, verbose_name='تلفن ثابت')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('activity_type', models.CharField(blank=True, max_length=150, verbose_name='نوع فعالیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('active', 'مشتری فعال'), ('inactive', 'مشتری غیرفعال'), ('dropped', 'منصرف شده')], default='new', max_length=20, verbose_name='وضعیت مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مبلغ کل')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('deposit', 'بیعانه پرداخت شده'), ('installment', 'قسطی'), ('settled', 'تسویه شده')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='کارمند مسئول')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='سمت')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='توضیحات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'فرد تماس',
                'verbose_name_plural': 'افراد تماس',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='شرح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'تاریخچه فعالیت\u200cها',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'مدیر'), ('employee', 'کارمند'), ('support', 'پشتیبان'), ('sales', 'فروش')], default='employee', max_length=20, verbose_name='نقش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کارمند',
                'verbose_name_plural': 'کارکنان (نقش\u200cها)',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ')),
                ('method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت به کارت'), ('pos', 'کارتخوان'), ('cheque', 'چک'), ('other', 'سایر')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='توضیحات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='crm.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'درخواست / مشکل',
                'verbose_name_plural': 'درخواست\u200cها / مشکلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_purchased', models.BooleanField(default=False, help_text='اگر تیک نخورد یعنی مشتری فقط در حال بررسی است', verbose_name='خریداری شده')),
                ('sale_status', models.CharField(choices=[('initial', 'درخواست اولیه'), ('reviewing', 'در حال بررسی'), ('introduced', 'نرم\u200cافزار معرفی شد'), ('waiting_decision', 'منتظر تصمیم مشتری'), ('waiting_payment', 'در انتظار پرداخت'), ('purchased', 'خریداری شد'), ('dropped', 'منصرف شد')], default='initial', max_length=20, verbose_name='وضعیت فروش')),
                ('drop_reason', models.CharField(blank=True, choices=[('price', 'قیمت'), ('other_software', 'انتخاب نرم\u200cافزار دیگر'), ('no_need', 'فعلاً نیاز ندارد'), ('other_company', 'خرید از شرکت دیگر'), ('other', 'سایر')], max_length=20, verbose_name='دلیل انصراف')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='توضیحات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='crm.customer', verbose_name='مشتری')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.software', verbose_name='نرم\u200cافزار')),
            ],
            options={
                'verbose_name': 'نرم\u200cافزار مشتری',
                'verbose_name_plural': 'نرم\u200cافزارهای مشتری',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کار')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='موعد')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='ساعت')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('waiting_customer', 'منتظر مشتری'), ('waiting_colleague', 'منتظر همکار'), ('needs_followup', 'نیاز به پیگیری'), ('done', 'انجام شد'), ('canceled', 'لغو شد')], default='new', max_length=20, verbose_name='وضعیت')),
                ('result', models.CharField(blank=True, max_length=250, verbose_name='نتیجه')),
                ('result_note', models.TextField(blank=True, verbose_name='توضیحات نتیجه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اتمام')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.customer', verbose_name='مشتری')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.request', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'وظیفه / پیگیری',
                'verbose_name_plural': 'وظایف و پیگیری\u200cها',
                'ordering': ['due_date', 'due_time'],
            },
        ),
    ]
