# Generated by Django 6.1.1 on 2026-10-01 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نام گروه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('members', models.ManyToManyField(blank=True, related_name='crm_groups', to=settings.AUTH_USER_MODEL, verbose_name='اعضا')),
            ],
            options={
                'verbose_name': 'گروه کاری',
                'verbose_name_plural': 'گروه\u200cهای کاری',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.workgroup', verbose_name='گروه کاری'),
        ),
    ]
