# Generated by Django 6.1.1 on 2026-09-21 05:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثلاً: USD ، AED ، IRT', max_length=10, unique=True, verbose_name='کد ارز')),
                ('name', models.CharField(help_text='مثلاً: دلار آمریکا، درهم امارات، تومان', max_length=100, verbose_name='نام واحد')),
                ('symbol', models.CharField(blank=True, help_text='مثلاً: $ یا د.إ یا تومان', max_length=10, verbose_name='نماد/علامت')),
                ('rate_to_toman', models.DecimalField(decimal_places=2, help_text='هر یک واحد از این ارز معادل چند تومان است؟ (برای خود تومان مقدار 1 وارد کنید)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='نرخ برابری با تومان')),
                ('is_default', models.BooleanField(default=False, help_text='در صورت فعال بودن، به\u200cعنوان واحد پیش\u200cفرض نمایش قیمت\u200cها استفاده می\u200cشود', verbose_name='واحد پیش\u200cفرض فروشگاه')),
                ('auto_update', models.BooleanField(default=False, help_text='این گزینه برای آینده رزرو شده؛ فعلاً همه\u200cی نرخ\u200cها دستی وارد می\u200cشوند', verbose_name='دریافت خودکار نرخ از اینترنت (به\u200cزودی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'واحد پول',
                'verbose_name_plural': 'واحدهای پول',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='اسلاگ (آدرس صفحه)')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='کد کالا (SKU)')),
                ('short_description', models.CharField(blank=True, help_text='در لیست کالاها نمایش داده می\u200cشود', max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کامل')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر کالا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / نمایش در فروشگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sales.category', verbose_name='دسته\u200cبندی')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sales.currency', verbose_name='واحد قیمت')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ویژگی')),
                ('value', models.CharField(max_length=300, verbose_name='مقدار')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='sales.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'ویژگی کالا',
                'verbose_name_plural': 'ویژگی\u200cهای کالا',
                'ordering': ['order', 'id'],
            },
        ),
    ]
